repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 5403c16080c62d2568b9adab14249214641a9d1a # 0.12.21
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: a56c0b927e6465d37cae3e97d35d4d18ab2b96cd # v0.16.9
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format
