repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: e3f880aff673113aeb3e424ea3ee58e2807f9453 # 0.12.11
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 321478e58f4938179c6b86e4ddfa923d1547a49b # v0.16.6
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format
