repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: eec2b3c4f52295313b08b04f928ab2479e468b5c # 0.12.15
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: e8f7d69b957a30acb2c875078d5fd012de24b64c # v0.16.7
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format
